[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
sea-orm.workspace = true
log.workspace = true
chrono.workspace = true
async-trait.workspace = true
